---
- name: Create default app-server directory
  file: 
    path: /var/was-liberty
    state: directory

- name: Spin up Websphere liberty Application Server
  docker_container:
    name: nazars-was-liberty
    image: websphere-liberty:{{was_liberty_tag}}
    state: started
    ports:
      - "{{ wlp_http_port }}:9080" #HTTP port
      - "{{ wlp_https_port }}:9443" #HTTPS port
    volumes:
      - "/var/was-liberty:/config"
  tags:
    - was

- name: Take ownership of ../was-liberty/ dir
  file:
    path: /var/was-liberty/
    recurse: yes
    mode: 0777
    state: directory


