---
- name: Create docker user-defined network
  docker_network:
    name: keycloak-network

- name: Start MYSQL instance for keycloak
  docker_container:
    name: keycloak-mysql
    image: mysql
    volumes:
      - /var/lib/keycloak/mysql:/var/lib/mysql
    networks:
      - name: "keycloak-network"
    exposed_ports:
      - "{{keycloak_db_port}}:3306"
    env:
      MYSQL_DATABASE: "{{ keycloak_db_name }}"
      MYSQL_USER: "{{ keycloak_db_user }}"
      MYSQL_PASSWORD: "{{ keycloak_db_pw }}"
      MYSQL_ROOT_PASSWORD: "{{ keycloak_db_root_pw }}"

- name: Start Keycloak instance
  docker_container:
    name: keycloak
    image: jboss/keycloak
    volumes:
      - /var/lib/keycloak:/opt/jboss/keycloak
    exposed_ports:
      - "{{keycloak_port}}:8080"
    networks:
      - name: "keycloak-network"
    env:
      JDBC_PARAMS: 'connectionTimeout=30'