---
- name: Create keycloak dir /var/lib/keycloak
  file:
    path: /var/lib/keycloak
    state: directory

- name: Create gitlab dir /var/lib/kecloak/psql
  file:
    path: /var/lib/keycloak/psql
    state: directory

- name: Create docker user-defined network
  docker_network:
    name: keycloak-network

- name: Start PSQL instance for keycloak
  docker_container:
    name: keycloak-psql
    image: postgres
    state: started
    volumes:
      - /var/lib/keycloak/psql:/var/lib/psql
    networks:
      - name: "keycloak-network"
    ports:
      - "{{ keycloak_db_port }}:5432"
    env:
      POSTGRES_DATABASE: "{{ keycloak_db_name }}"
      POSTGRES_USER: "{{ keycloak_db_user }}"
      POSTGRES_PASSWORD: "{{ keycloak_db_pw }}"

- name: Start Keycloak instance
  docker_container:
    name: keycloak
    image: 'jboss/keycloak'
    state: started
    ports:
      - "{{ keycloak_port }}:8080"
    networks:
      - name: "keycloak-network"
    env:
      KEYCLOAK_USER: "{{ keycloak_user }}"
      KEYCLOAK_PASSWORD: "{{ keycloak_pw }}"
      DB_USER: "{{ keycloak_db_user }}"
      DB_PASSWORD: "{{ keycloak_db_pw }}"
      DB_ADDR: keycloak-psql
      DB_VENDOR: postgres