---
- hosts: master
  remote_user: nazars
  become: yes
  vars_files:
    - ../inventory/group_vars/rbs-vars.yml
  roles: 
    - common/misc #Install first as dependencies may occure below
    - common/python
    - common/openjdk
    - common/docker
    - common/jenkins
    - common/maven
    - master/redis
    - master/gitlab
    - master/keycloak
    #- master/openshift
    #- master/websphere_liberty