---
openshift_install_folder: openshift-origin-client-tools-v3.9.0-191fece-linux-64bit
openshift_install_url: https://github.com/openshift/origin/releases/download/v3.9.0/{{openshift_install_folder}}.tar.gz